name: Setup Anbox with VNC and ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-anbox:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies tightvncserver novnc websockify wget unzip snapd curl software-properties-common dkms build-essential

    - name: Build and Load Kernel Modules
      run: |
        # Baixando e construindo os m贸dulos ashmem e binder
        git clone https://github.com/anbox/anbox-modules.git
        cd anbox-modules
        # Construindo m贸dulo binder
        cd binder
        make
        sudo insmod binder_linux.ko
        cd ..
        # Construindo m贸dulo ashmem
        cd ashmem
        make
        sudo insmod ashmem_linux.ko
        cd ..
        # Instalando os m贸dulos para serem carregados automaticamente
        sudo cp -v binder/binder_linux.ko /lib/modules/$(uname -r)/extra/
        sudo cp -v ashmem/ashmem_linux.ko /lib/modules/$(uname -r)/extra/
        sudo depmod -a

    - name: Install Anbox
      run: |
   
